name: Fetch and Download Workflows
on:
  workflow_dispatch:
    inputs:
      repo_branch_list:
        description: 'Comma-separated list of repositories and branches (e.g. org/repo1:main,org/repo2:develop)'
        required: true
        default: Ravicharan-nettyam/template-repo:main
jobs:
  fetch-and-download-workflows:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install requests
      run: pip install requests

    - name: Fetch and download workflows from repositories
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
        REPO_BRANCH_LIST: ${{ github.event.inputs.repo_branch_list }}      
      run: python fetch_workflows1.py

    - name: Checking Downloaded workflows
      run: ls -l .github/workflows/

    - name: Git status Check
      run: git status

    - name: Commit downloaded workflows to .github/workflows
      env:
        GITHUB_TOKEN: ${{ secrets.MY_PAT }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .github/workflows/*
        git commit -m "Downloaded workflows from multiple repositories" || echo "Nothing to Commit"
        git push || echo "Nothing to push"